project:
  type: website
  output-dir: docs
website:
  title: "Ankit Borle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    



