project:
  type: website
  output-dir: docs
  
website:
  title: "Ankit Borle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Pages/MidProject.qmd
      - Pages/Code.qmd
      - Pages/FinalProject.qmd
      - Pages/FinalCode.qmd

format:
  html:
    html_preserve: true
    mainfont: times new roman
    fontsize: 1.5rem
    fontcolor: "#043850"
    linkcolor: "#2a8d25"
    monofont: courier view
    css: FinalProj.css
    



