project:
  type: website
  output-dir: docs
website:
  title: "Ankit Borle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Pages/MidProject.qmd
      - Pages/Code.qmd

format:
  html:
    theme: sandstone
    mainfont: times new roman
    fontsize: 1.5rem
    fontcolor: "#043850"
    linkcolor: "#2a8d25"
    monofont: courier view
    css: styles.css
    



